### ISSUE TITLE
Create diagrams of unit trees for paper

### ISSUE THREAD

**Issue by tgroechel** [interaction-lab/BT-Espressissimo#50]
Create diagrams of the unit tree tests. I would use maybe something like draw.io or you can use dot trees. These will be added into the paper graphically. You might also look into using the latex graphics packages but it may be cumbersome.

**Comment by cmkuo12** [comment]
Diagrams Link: https://drive.google.com/file/d/1v3FLLLFx8y8aIAR8EbUeHGI8gGyCVmRT/view?usp=sharing
(I believe that it should be editable)

Doc Link (tree screenshots): https://docs.google.com/document/d/1WL2wV-Ae-0gpV35rprawodJTEh7tCcBCGLL5q3YWbLY/edit

**Comment by tgroechel** [comment]
Added some trees, will discuss Wednesday:
- [ ] go over trees
- [ ] how this will go into the paper

**Comment by tgroechel** [comment]
Trees are done, this issue will live for the docs, moving from "unit trees" to "base behavior trees" or other better name
