### ISSUE TITLE
Create unit trees and generate data

### ISSUE THREAD

**Issue by tgroechel** [interaction-lab/BT-Espressissimo#54]

**Comment by tgroechel** [comment]
#50 has the tree links, need to 
- [ ] change the conditions/action to be generic
- [ ] make `time` configurable (how many rows of data)
- [ ] create the trees in config files
- [ ] generate the data
- [ ] run on pipeline

**Comment by cmkuo12** [comment]
Created a success/fail column for logging robot action results, but unsure of how to write to csv from within the tree to log every action

**Comment by tgroechel** [comment]
Confirm it works, usage needs a readme as 'python3 bt_sim.py path/to/config' and edit number of rows in the 'globals.py'
